/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TestingEngineRouteImport } from './routes/testing-engine'
import { Route as SystemEventsRouteImport } from './routes/system-events'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProductivityRouteImport } from './routes/productivity'
import { Route as PcAutomationRouteImport } from './routes/pc-automation'
import { Route as McpPluginsRouteImport } from './routes/mcp-plugins'
import { Route as ImageGenerationRouteImport } from './routes/image-generation'
import { Route as DoctorAssistantRouteImport } from './routes/doctor-assistant'
import { Route as CodingRouteImport } from './routes/coding'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as AutomationRouteImport } from './routes/automation'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingEngineRoute = TestingEngineRouteImport.update({
  id: '/testing-engine',
  path: '/testing-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemEventsRoute = SystemEventsRouteImport.update({
  id: '/system-events',
  path: '/system-events',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductivityRoute = ProductivityRouteImport.update({
  id: '/productivity',
  path: '/productivity',
  getParentRoute: () => rootRouteImport,
} as any)
const PcAutomationRoute = PcAutomationRouteImport.update({
  id: '/pc-automation',
  path: '/pc-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const McpPluginsRoute = McpPluginsRouteImport.update({
  id: '/mcp-plugins',
  path: '/mcp-plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageGenerationRoute = ImageGenerationRouteImport.update({
  id: '/image-generation',
  path: '/image-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAssistantRoute = DoctorAssistantRouteImport.update({
  id: '/doctor-assistant',
  path: '/doctor-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingRoute = CodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/automation': typeof AutomationRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/coding': typeof CodingRoute
  '/doctor-assistant': typeof DoctorAssistantRoute
  '/image-generation': typeof ImageGenerationRoute
  '/mcp-plugins': typeof McpPluginsRoute
  '/pc-automation': typeof PcAutomationRoute
  '/productivity': typeof ProductivityRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/system-events': typeof SystemEventsRoute
  '/testing-engine': typeof TestingEngineRoute
  '/vision': typeof VisionRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/automation': typeof AutomationRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/coding': typeof CodingRoute
  '/doctor-assistant': typeof DoctorAssistantRoute
  '/image-generation': typeof ImageGenerationRoute
  '/mcp-plugins': typeof McpPluginsRoute
  '/pc-automation': typeof PcAutomationRoute
  '/productivity': typeof ProductivityRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/system-events': typeof SystemEventsRoute
  '/testing-engine': typeof TestingEngineRoute
  '/vision': typeof VisionRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/automation': typeof AutomationRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/coding': typeof CodingRoute
  '/doctor-assistant': typeof DoctorAssistantRoute
  '/image-generation': typeof ImageGenerationRoute
  '/mcp-plugins': typeof McpPluginsRoute
  '/pc-automation': typeof PcAutomationRoute
  '/productivity': typeof ProductivityRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/system-events': typeof SystemEventsRoute
  '/testing-engine': typeof TestingEngineRoute
  '/vision': typeof VisionRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/automation'
    | '/browser'
    | '/chat'
    | '/coding'
    | '/doctor-assistant'
    | '/image-generation'
    | '/mcp-plugins'
    | '/pc-automation'
    | '/productivity'
    | '/research'
    | '/settings'
    | '/system-events'
    | '/testing-engine'
    | '/vision'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/automation'
    | '/browser'
    | '/chat'
    | '/coding'
    | '/doctor-assistant'
    | '/image-generation'
    | '/mcp-plugins'
    | '/pc-automation'
    | '/productivity'
    | '/research'
    | '/settings'
    | '/system-events'
    | '/testing-engine'
    | '/vision'
    | '/voice'
  id:
    | '__root__'
    | '/automation'
    | '/browser'
    | '/chat'
    | '/coding'
    | '/doctor-assistant'
    | '/image-generation'
    | '/mcp-plugins'
    | '/pc-automation'
    | '/productivity'
    | '/research'
    | '/settings'
    | '/system-events'
    | '/testing-engine'
    | '/vision'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AutomationRoute: typeof AutomationRoute
  BrowserRoute: typeof BrowserRoute
  ChatRoute: typeof ChatRoute
  CodingRoute: typeof CodingRoute
  DoctorAssistantRoute: typeof DoctorAssistantRoute
  ImageGenerationRoute: typeof ImageGenerationRoute
  McpPluginsRoute: typeof McpPluginsRoute
  PcAutomationRoute: typeof PcAutomationRoute
  ProductivityRoute: typeof ProductivityRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  SystemEventsRoute: typeof SystemEventsRoute
  TestingEngineRoute: typeof TestingEngineRoute
  VisionRoute: typeof VisionRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing-engine': {
      id: '/testing-engine'
      path: '/testing-engine'
      fullPath: '/testing-engine'
      preLoaderRoute: typeof TestingEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-events': {
      id: '/system-events'
      path: '/system-events'
      fullPath: '/system-events'
      preLoaderRoute: typeof SystemEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productivity': {
      id: '/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof ProductivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc-automation': {
      id: '/pc-automation'
      path: '/pc-automation'
      fullPath: '/pc-automation'
      preLoaderRoute: typeof PcAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-plugins': {
      id: '/mcp-plugins'
      path: '/mcp-plugins'
      fullPath: '/mcp-plugins'
      preLoaderRoute: typeof McpPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-generation': {
      id: '/image-generation'
      path: '/image-generation'
      fullPath: '/image-generation'
      preLoaderRoute: typeof ImageGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-assistant': {
      id: '/doctor-assistant'
      path: '/doctor-assistant'
      fullPath: '/doctor-assistant'
      preLoaderRoute: typeof DoctorAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding': {
      id: '/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AutomationRoute: AutomationRoute,
  BrowserRoute: BrowserRoute,
  ChatRoute: ChatRoute,
  CodingRoute: CodingRoute,
  DoctorAssistantRoute: DoctorAssistantRoute,
  ImageGenerationRoute: ImageGenerationRoute,
  McpPluginsRoute: McpPluginsRoute,
  PcAutomationRoute: PcAutomationRoute,
  ProductivityRoute: ProductivityRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  SystemEventsRoute: SystemEventsRoute,
  TestingEngineRoute: TestingEngineRoute,
  VisionRoute: VisionRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
